### ISSUE TITLE
Typescript types are broken.

### ISSUE THREAD

**Issue by burtonator** [jxson/front-matter#61] opened 2019-11-20 03:04 UTC
The types exported are broken I think... Once you put the test() method on FM it breaks and TS can't compile due to "has no call signatures".

You might want to just export two functions in a namespace or a class.

You should also export FrontMatterResult so that it's easily usable as in interface in someone else's code.

**Comment by kubosho** [comment] 2020-05-13 15:22
> You should also export FrontMatterResult so that it's easily usable as in interface in someone else's code.

This request is fixed on https://github.com/jxson/front-matter/pull/63.

**Comment by jxson** [comment] 2020-05-13 18:12
Thanks @kubosho

**Comment by jxson** [comment] 2020-05-13 18:16
I am assuming the issue is resolved with #63, if this is not the case let me know.

For context, I am not familiar with TS so if there is anyone interested in helping with verifying this module is compatible with TS user expectations it would be greatly appreciated.

**Closed by jxson** 2020-05-13 18:16 UTC

**Comment by tyankatsu0105** [comment] 2020-05-15 15:17
@jxson 
[check-dts](https://github.com/ai/check-dts) helps us to check whether declaration is correct.
I'll send PR someday👍
